apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: '{{ include "simple-api.fullname" . }}-gcpsm-store'
  namespace: simple-api
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.clusterSecretStore.projectId }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.clusterSecretStore.location }}
          clusterName: {{ .Values.clusterSecretStore.clusterName }}
          serviceAccountRef:
            name: '{{ include "simple-api.fullname" . }}-eso-ksa'
            namespace: external-secrets
