apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "simple-api.fullname" . }}-config"
data:
  PORT: "{{ .Values.config.PORT }}"
  RUST_LOG: "{{ .Values.config.RUST_LOG }}"
  SAMPLE_ENV: "{{ .Values.config.SAMPLE_ENV }}"
