apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-api.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}

  selector:
    matchLabels:
      app: {{ include "simple-api.fullname" . }}

  template:
    metadata:
      labels:
        app: {{ include "simple-api.fullname" . }}

    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ include "simple-api.fullname" . }}
                topologyKey: "kubernetes.io/hostname"

      containers:
        - name: {{ include "simple-api.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.config.PORT }}

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.config.PORT }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.config.PORT }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false

          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: '{{ include "simple-api.fullname" . }}-config'
                  key: PORT
            - name: RUST_LOG
              valueFrom:
                configMapKeyRef:
                  name: '{{ include "simple-api.fullname" . }}-config'
                  key: RUST_LOG
            - name: SAMPLE_ENV
              valueFrom:
                configMapKeyRef:
                  name: '{{ include "simple-api.fullname" . }}-config'
                  key: SAMPLE_ENV
          envFrom:
            - secretRef:
                name: '{{ include "simple-api.fullname" . }}-secret'
