apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "simple-api.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.classNameAnnotation }}
    networking.gke.io/redirect-http-to-https: "{{ .Values.ingress.redirectToHttps }}"
    networking.gke.io/managed-certificates: '{{ include "simple-api.fullname" . }}-cert'
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "simple-api.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
