{{- range $name, $app := .Values.apps }}
{{- if $app.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name | default $name }}
  namespace: argocd
spec:
  project: {{ $app.project | default "default" }}
  source:
    repoURL: {{ $app.source.repoUrl | quote }}
    targetRevision: {{ $app.source.targetRevision | quote }}
    path: {{ $app.source.path | quote }}
    helm:
      valueFiles:
      {{- range $file := $app.source.valueFiles }}
        - {{ $file | quote }}
      {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $app.destination.namespace | quote }}
  syncPolicy:
  {{- if $app.syncPolicy.automated.enabled }}
    automated:
      prune: {{ $app.syncPolicy.automated.prune | default true }}
      selfHeal: {{ $app.syncPolicy.automated.selfHeal | default true }}
  {{- end }}
    syncOptions:
    {{- range $opt := $app.syncPolicy.syncOptions }}
      - {{ $opt | quote }}
    {{- end }}
---
{{- end}}
{{- end }}
