replicaCount: 2
rollingUpdate:
  maxUnavailable: 0
  maxSurge: 1
image:
  repository: asia-northeast1-docker.pkg.dev/gke-simple-api/simple-api/simple-api
  tag: ddce6ded1ca25b02f934c779235a4a7b318dfc48
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 7878
  nodePort: null
ingress:
  classNameAnnotation: gce
  redirectToHttps: true
  host: 'tsunaga2.xyz'
managedCertificate:
  domain: 'tsunaga2.xyz'
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
probes:
  path: /healthcheck
  readiness:
    initialDelaySeconds: 3
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 3
  liveness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 5
terminationGracePeriodSeconds: 30
pdb:
  enabled: true
  minAvailable: 1
config:
  PORT: 7878
  RUST_LOG: info
  SAMPLE_ENV: this-is-sample-env-value
eso:
  serviceAccount: "eso-secret-manager@gke-simple-api.iam.gserviceaccount.com"
clusterSecretStore:
  projectId: gke-simple-api
  location: asia-northeast1
  clusterName: simple-api
  serviceAccountName: "eso-secret-manager@gke-simple-api.iam.gserviceaccount.com"
  storeName:
secret:
  secretManagerId: simple-api-secret
