name: Build image

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: gke-simple-api
  REGION: asia-northeast1
  IMAGE_NAME: asia-northeast1-docker.pkg.dev/gke-simple-api/simple-api/simple-api
  WORKLOAD_IDENTITY_PROVIDER: "projects/326015383394/locations/global/workloadIdentityPools/github-pool/providers/github-pool-provider"
  SERVICE_ACCOUNT: "cicd-build@gke-simple-api.iam.gserviceaccount.com"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate google cloud
        uses: google-github-actions/auth@v3
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Setup sdk
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Setup docker
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Configure docker
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Set image tag
        id: vars
        run: |
          TAG="${GITHUB_SHA}"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
